version: "3"

services:
  consul:
    image: consul:latest
    container_name: consul
    command: "agent -server -bootstrap -ui -node=consul-server-leader -client=0.0.0.0"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8500:8500"
    networks:
      - microservice

  server1:
    build:
      context: .
    container_name: "server1"
    command: "php bin/hyperf.php start"
    depends_on:
      - "consul"
    volumes:
      - ./www/server1:/var/www
    ports:
    - 9511:9502
    networks:
      - microservice
    tty: true

  server2:
    build:
      context: .
    container_name: "server2"
    command: "php bin/hyperf.php start"
    depends_on:
      - "consul"
    volumes:
      - ./www/server2:/var/www
    networks:
      - microservice
    tty: true

  api:
    build:
      context: .
    container_name: "api"
    command: "php bin/hyperf.php start"
    depends_on:
      - "server1"
      - "server2"
    volumes:
      - ./www/api:/var/www
    ports:
      - "9507:9501"
    networks:
      - microservice
    tty: true
#
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    networks:
#      - microservice
#
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#    networks:
#      - microservice

networks:
  microservice:
    driver: bridge

volumes:
  microservice:
    driver: local